### GET request for getting all users
GET http://localhost:4000/user
Content-Type: application/json



### POST request for creating a new user
POST http://localhost:4000/user
Content-Type: application/json

{
  "name": {
    "first": "kals",
    "last": "fka"
  },
  "email": "ddsadj@gmail.com",
  "phone": "634-343-4549"
}
